<<<<<<< HEAD

package logView;


public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
=======
package logView;

import javax.swing.*;
import java.awt.*;

public class view extends JFrame {

    private JTextField jTextField1;
    private JPasswordField jPasswordField1;
    private JButton jButtonEntrar;
    private JButton jButtonCadastro;
    private JLabel jLabel1;

>>>>>>> upstream/main
    public view() {
        initComponents();
    }

<<<<<<< HEAD
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonENTRAR = new javax.swing.JButton();
        jButtonCADASTRO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 210, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 210, -1));

        jButtonENTRAR.setContentAreaFilled(false);
        jButtonENTRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 200, 50));

        jButtonCADASTRO.setContentAreaFilled(false);
        jButtonCADASTRO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCADASTROActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCADASTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/usuárioLogin (1).jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1180, 799));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1828, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENTRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonENTRARActionPerformed

    private void jButtonCADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCADASTROActionPerformed
        cadastroView TelaDeCadastro = new cadastroView();
        TelaDeCadastro.setVisible(true);
    }//GEN-LAST:event_jButtonCADASTROActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCADASTRO;
    private javax.swing.JButton jButtonENTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
=======
    private void initComponents() {
        jTextField1 = new JTextField();
        jPasswordField1 = new JPasswordField();
        jButtonEntrar = new JButton("Entrar");
        jButtonCadastro = new JButton("Cadastro");
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new Dimension(500, 300));

        // Configurando os componentes
        jTextField1.setFont(new Font("Gill Sans MT", Font.PLAIN, 14));
        jLabel1.setIcon(new ImageIcon("resources/imagem/usuarioLogin.jpg")); // Atualize o caminho da imagem se necessário
        jLabel1.setPreferredSize(new Dimension(1180, 799));

        jButtonEntrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonEntrar.addActionListener(evt -> jButtonEntrarActionPerformed(evt));

        jButtonCadastro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonCadastro.addActionListener(evt -> jButtonCadastroActionPerformed(evt));

        // Usando GroupLayout
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(760, 760, 760)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addComponent(jPasswordField1)
                                        .addComponent(jButtonEntrar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCadastro, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonEntrar, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonCadastro, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: Adicione lógica de tratamento aqui
    }

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: Adicione lógica de tratamento aqui
    }

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {
        cadastroView telaDeCadastro = new cadastroView();
        telaDeCadastro.setVisible(true);
    }

    public static void main(String[] args) {
        EventQueue.invokeLater(() -> new view().setVisible(true));
    }
>>>>>>> upstream/main
}
